configfile: "config/SraAccList.yaml"

GENOME_VERSION = "GRCh38"
ENSEMBL_VERSION = "103"
SPECIES = config["species"]
SPECIES_LOWER = SPECIES.lower()
REF = f"{SPECIES}.{GENOME_VERSION}"
GENEMODEL_VERSION = f"{GENOME_VERSION}.{ENSEMBL_VERSION}"
GENOME_FA = f"../resources/ensembl/Homo_sapiens.{GENOME_VERSION}.dna.primary_assembly.fa"
ENSEMBL_GFF = f"../resources/ensembl/Homo_sapiens.{GENEMODEL_VERSION}.gff3"
REFSTAR_PREFIX = f"../resources/ensembl/Homo_sapiens.{GENEMODEL_VERSION}RsemStar/RsemStarReference"
REFSTAR_FOLDER = f"../resources/ensembl/Homo_sapiens.{GENEMODEL_VERSION}RsemStar/"
REF_PREFIX = f"../resources/ensembl/Homo_sapiens.{GENEMODEL_VERSION}Rsem/RsemReference"
REF_FOLDER = f"../resources/ensembl/Homo_sapiens.{GENEMODEL_VERSION}Rsem/"
STAR_REF_FOLDER = f"../resources/ensembl/Homo_sapiens.{GENEMODEL_VERSION}Star" # no slash

rule all:
    input: "../results/quant/Counts.csv", "../results/quant/Counts_Isoforms.csv"

include: "rules/downloads.smk"
include: "rules/quant.smk"
