channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - python =3.7
  - rsem =1.3.2-0
  - samtools =1.9
  - git
  - fastqc
  - fastp
  - sra-tools
  - star =2.7.0f-0
  - numpy
  - biopython
  - bcbio-gff
  - pandas
