channels:
  - bioconda
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - rsem =1.3.3
  - star =2.7.9a
  - git
  - fastp
  - sra-tools =2.10
  - biopython
  - gzip
  - wget
  - gdown
  - scvelo==0.2.3
  - velocyto.py==0.17.17
  - pytables # scvelo
  - louvain # sccvelo
  - entrez-direct # for srr_lookup
